import type { Channel } from "../types/channel";

export const CHANNELS: Channel[] = [
  // COMMUNITY
  {
    id: "general",
    name: "general",
    description: "General community discussion",
    icon: "hash",
    category: "community",
    online: true,
    unreadCount: 3,
  },
  {
    id: "introductions",
    name: "introductions",
    description: "Introduce yourself to the community",
    icon: "users",
    category: "community",
    online: true,
    unreadCount: 0,
  },
  {
    id: "help",
    name: "help",
    description: "Ask questions and get unstuck",
    icon: "hash",
    category: "community",
    online: true,
    unreadCount: 0,
  },
  {
    id: "random",
    name: "random",
    description: "Off-topic conversations and community chat",
    icon: "hash",
    category: "community",
    online: true,
    unreadCount: 0,
  },
  {
    id: "showcase",
    name: "showcase",
    description: "Share projects, ideas, and achievements",
    icon: "code",
    category: "community",
    online: true,
    unreadCount: 0,
  },

  // DEVELOPMENT
  {
    id: "python",
    name: "python",
    description: "Python programming",
    icon: "code",
    category: "development",
    online: true,
    unreadCount: 0,
  },
  {
    id: "javascript",
    name: "javascript",
    description: "JavaScript programming and development",
    icon: "code",
    category: "development",
    online: true,
    unreadCount: 0,
  },
  {
    id: "typescript",
    name: "typescript",
    description: "TypeScript development and best practices",
    icon: "code",
    category: "development",
    online: true,
    unreadCount: 0,
  },
  {
    id: "react",
    name: "react",
    description: "React development and component architecture",
    icon: "code",
    category: "development",
    online: true,
    unreadCount: 0,
  },
  {
    id: "nextjs",
    name: "nextjs",
    description: "Next.js development and applications",
    icon: "code",
    category: "development",
    online: true,
    unreadCount: 0,
  },
  {
    id: "nodejs",
    name: "nodejs",
    description: "Node.js and backend JavaScript",
    icon: "server",
    category: "development",
    online: true,
    unreadCount: 0,
  },
  {
    id: "webdev",
    name: "webdev",
    description: "Web development and modern web technologies",
    icon: "code",
    category: "development",
    online: true,
    unreadCount: 0,
  },
  {
    id: "api",
    name: "api",
    description: "APIs, integrations, and backend services",
    icon: "network",
    category: "development",
    online: true,
    unreadCount: 0,
  },

  // DATA & AI
  {
    id: "sql",
    name: "sql",
    description: "SQL and databases",
    icon: "database",
    category: "data-ai",
    online: true,
    unreadCount: 0,
  },
  {
    id: "data-science",
    name: "data-science",
    description: "Data science, analysis, and statistics",
    icon: "brain",
    category: "data-ai",
    online: true,
    unreadCount: 0,
  },
  {
    id: "machine-learning",
    name: "machine-learning",
    description: "Machine learning concepts and projects",
    icon: "brain",
    category: "data-ai",
    online: true,
    unreadCount: 0,
  },
  {
    id: "ai",
    name: "ai",
    description: "Artificial intelligence and emerging AI technologies",
    icon: "brain",
    category: "data-ai",
    online: true,
    unreadCount: 0,
  },
  {
    id: "data-engineering",
    name: "data-engineering",
    description: "Data pipelines, platforms, and infrastructure",
    icon: "database",
    category: "data-ai",
    online: true,
    unreadCount: 0,
  },

  // COMPUTING
  {
    id: "dsa",
    name: "dsa",
    description: "Data structures and algorithms",
    icon: "git-fork",
    category: "computing",
    online: true,
    unreadCount: 0,
  },
  {
    id: "algorithms",
    name: "algorithms",
    description: "Algorithm design, problem solving, and analysis",
    icon: "brain",
    category: "computing",
    online: true,
    unreadCount: 0,
  },
  {
    id: "system-design",
    name: "system-design",
    description: "Scalable systems and architecture",
    icon: "server",
    category: "computing",
    online: true,
    unreadCount: 0,
  },
  {
    id: "databases",
    name: "databases",
    description: "Database systems, design, and optimization",
    icon: "database",
    category: "computing",
    online: true,
    unreadCount: 0,
  },
  {
    id: "computer-networks",
    name: "computer-networks",
    description: "Networking concepts and infrastructure",
    icon: "network",
    category: "computing",
    online: true,
    unreadCount: 0,
  },
  {
    id: "operating-systems",
    name: "operating-systems",
    description: "Operating systems and low-level computing",
    icon: "cpu",
    category: "computing",
    online: true,
    unreadCount: 0,
  },

  // CAREER
  {
    id: "jobs",
    name: "jobs",
    description: "Job opportunities and career openings",
    icon: "briefcase",
    category: "career",
    online: true,
    unreadCount: 0,
  },
  {
    id: "interviews",
    name: "interviews",
    description: "Interview preparation and experiences",
    icon: "users",
    category: "career",
    online: true,
    unreadCount: 0,
  },
  {
    id: "mentorship",
    name: "mentorship",
    description: "Find mentors and share your experience",
    icon: "users",
    category: "career",
    online: true,
    unreadCount: 0,
  },
  {
    id: "pairing",
    name: "pairing",
    description: "Find a study or coding partner",
    icon: "users",
    category: "career",
    online: true,
    unreadCount: 0,
  },
  {
    id: "hackathons",
    name: "hackathons",
    description: "Hackathons, teams, ideas, and collaboration",
    icon: "code",
    category: "career",
    online: true,
    unreadCount: 0,
  },
];
